"use client";

import Footer from "./components/Footer";
// import "./index.css";
import "./fonts.css";
import affirm from "./affirm.js";

export const metadata = {
  title: "BodyBuilding and BS",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src={affirm}></script>
      </head>
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
